var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                         ooooo  ",
   "                                                                         ooooo  ",
   "                                                                         ooooo  ",
   "                                                                         ooooo  ",
   "                                                                    oo  xxxxxx  ",
   "                                                                xxxxxxxxxxx     ",
   "                                    o o                     o                   ",
   "                                                          xxxxxx                ",
   "                                   xxxxx             =                          ",
   "                                                   xxxxxx                   xx  ",
   "  xx           v              xxxx        o o                                x  ",
   "  x                     o               xxxxxxx                              x  ",
   "  x        b          xxxxxxx                                              o x  ",
   "  x                    !!!!!                                                 x  ",
   "  x  @            =                   s       =                  xxxxx       x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxxxxx   xxx     xxxxxxx   xxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxx                        xx!!!!!xxxxxxxxxxxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxx      oooooooooo        xxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxx         =     oooooo xxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                ",
   "                                                                                "],
  ["                xxxxxxx                                                                                      x!x  ",
   "             xxxx     xxxx                                                                                   x!x  ",
   "            xx           xx                                                                                  x!x  ",
   "           xx             xx                                                                                 x!x  ",
   "                                                                                                  o   o   o  x!x  ",
   "           oooo   ooo        xx                                    o   o                                    xx!x  ",
   "            ooooooo  oo        xx                                                             xxxxxxxxxxxxxxx!!x  ",
   "           xxxxxxxxxxxxx         xxxxxxx        xxxxxxx            x   x                        !!!!!!!!!!!!!!xx  ",
   "                                                             xx  |   |   |  xx            xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                              xx!!!!!!!!!!!xx            v                        ",
   "                                                               xxxx!!!!!xxxx                                      ",
   "                                                                  xxxxxxx        xxx         xxx                  ",
   "                                                                                 x x         x x                  ",
   "                                                                                   x         x                    ",
   "                                               x     x                             xx        x                    ",
   "                                               xx    x                             x         x                    ",
   "                                               x     x      o  o     x   x         x         x                    ",
   "                                               x     x               x   x         x         x                    ",
   "                                x   x          x =   x     xxxxxx    x   x   xxxxxxxxx       x                    ",
   "             xx      xxx        x o x          x    xx               x   x   x               x                    ",
   "     @       x         x                       x     x               x   x   x               x                    ",
   "    xxx      x         x        x   x          x                    x   xxxxx   xxxxxx      x                    ",
   "    x x      x         x       xx o xx         x       x             x     o     x x         x                    ",
   "!!!!x xxxxxxxx         x!!!!!!xx     xx!!!!!!!!xx    x!!!!!!!!!!     x     =     x x         x                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xx       xxxxxxxxxx     x!!!!!!!xx!     xxxxxxxxxxxxx xx  o o  xx                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!x                      xx!!!!!!xx !                    xxxxxxxxx                     ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!x                     xx!!!!!!xx  !                                                  ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx   !                                                  ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx    !                                                  ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx     !                                                  "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                             ",
   "                                                                                                              ",
   "                                                           !!!        !!!  xxx                                ",
   "                                                           !x!        !x!                                     ",
   "                                                           x          x                                      ",
   "                                                            x   oooo   x       xxx                            ",
   "                                                            x          x   x  x!!!x                           ",
   "                                                            xxxxxxxxxxxx       xxx                            ",
   "                                                  x   x                                                       ",
   "                                                                          xxxxx                               ",
   "                                                      x                 xx                                    ",
   "                                                      x                xx                                     ",
   "                                                      x               xx                                      ",
   "                                      x   x                         xx                                        ",
   "                                      x   x           x           x                                           ",
   "                                                                     o                                        ",
   "                                    xxx   xx                x                                                 ",
   "                              o      x                                                  xxx                   ",
   "                                      x   x           x              x                 x!!!x                  ",
   "                             xxx                 o o  x!!!!!!!!!!!!!!x                   vx                   ",
   "                             x xxx     xx                                      ",
   "                             x                 xxxxxxxxxxxxxxxxxxxxxxx                                        ",
   "                             xx           xx                                         xxx                      ",
   "  xxx                        x     x      x                                         x!!!x                xxx  ",
   "  x x                        x    xxx     x                                          xxx                 x x  ",
   "  x                          x    xxx     xxxxxx                         xxxxx                             x  ",
   "  x                          x                                                                             x  ",
   "  x                          xx                                          x x x                             x  ",
   "  x                                                                             x  ",
   "  x                                o o                                   x         xxx                     x  ",
   "  x                          xx                                        xxx       x!!!x          x         x  ",
   "  x               o           x    xxx                                  xxx        xxx          xxx        x  ",
   "  x          xx               xxxxxxxxxxxxx  x oo x              x oo  xxxxx                    xxx        x  ",
   "  x      @                                x!!x    x!!!!x    x!!!!x    xxxxxxx                    x         x  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                             ",
   "                                                                                                              "],
  ["                                                                                                  xxx x       ",
   "                                                                                                      x       ",
   "                                                                                                  xxxxx       ",
   "                                                                                                  x           ",
   "          o  o                                                                                    x xxx       ",
   "             o            o                                                                       x x x       ",
   "             o                                                                               o o oxxx x       ",
   "             xxxxxxxxx                                                                                x       ",
   "                                                              xxxxx xxxxx xxxxx x       xxx xxxxx xxxxx       ",
   "                                                                                                              ",
   "                          x                               x    x                                              ",
   "                                                                                                              ",
   "                          o                                                                                   ",
   "                                                          x                                                   ",
   "          o              xxx                                                                                  ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                          x                                                   ",
   "                   xxx                                                                                        ",
   "                                                                                                              ",
   "                     xxx     o                               x                                                ",
   "                   xxx   xxx                                                                                  ",
   "             xxx xxx      xxx    xxx                                                                          ",
   "               xxx          xxx                                 x                                             ",
   "             xxx              xxx                                                       x                     ",
   "  xxxxxxxxxxx                    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx            ",
   "  x                                                                                                           ",
   "  x                                                                                                           ",
   "  x  @               o     o     o                                       o                                    ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                o                 o",
   "        x=                  =                =x   x                     xxx                x         x       x",
   "        xxxxxxxxxxxxxxx        xxxxxxxxxxxxxxx    x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                      x!!!!!!!!x                   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                      xxxxxxxxxx                                                                                     "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
